inte = int(55.89)
deci = float(55)
mystr = str(908978)
print(inte)
print(deci)
print(mystr)
tupl = tuple("this is a tuple")
asci = chr(65)
print(tupl)
print(asci)
lis = list("This is a list")
print(lis)
num = ord('f')
print(num)
 

